server:
  port: 9099

spring:
  datasource:
    first:
      jdbc-url: jdbc:mysql://localhost:3306/springboot-learning?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: hoolai
      driver-class-name: com.mysql.jdbc.Driver
    second:
      jdbc-url: jdbc:mysql://localhost:3306/springboot-learning2?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: hoolai
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
